In [1]:
import nltk


In [2]:
from nltk.corpus import brown


In [3]:
brown.categories()

['adventure',
 'belles_lettres',
 'editorial',
 'fiction',
 'government',
 'hobbies',
 'humor',
 'learned',
 'lore',
 'mystery',
 'news',
 'religion',
 'reviews',
 'romance',
 'science_fiction']

In [4]:
data=brown.sents(categories=['adventure'])

In [5]:
print(data)

[['Dan', 'Morgan', 'told', 'himself', 'he', 'would', 'forget', 'Ann', 'Turner', '.'], ['He', 'was', 'well', 'rid', 'of', 'her', '.'], ...]


In [6]:
data[0]

['Dan',
 'Morgan',
 'told',
 'himself',
 'he',
 'would',
 'forget',
 'Ann',
 'Turner',
 '.']

In [7]:
document=""
for i in range(5):
    document+=" ".join(data[i])
print(document)

Dan Morgan told himself he would forget Ann Turner .He was well rid of her .He certainly didn't want a wife who was fickle as Ann .If he had married her , he'd have been asking for trouble .But all of this was rationalization .


- Data Collection
- Tokenization    ### Break into small parts
- Stopword Removal ### Remove words unnecessary
- Stemming,Lemmatization
- Build a common Vocab
- Vectorise Sentences
- Machine Learning Modelling

In [8]:
from nltk.tokenize import sent_tokenize, word_tokenize

In [9]:
text="What are you doing? I guess you're learning Ml.It is quite an interesting field."

In [10]:
sents=sent_tokenize(text)

In [11]:
print(sents)

['What are you doing?', "I guess you're learning Ml.It is quite an interesting field."]


In [12]:
words=word_tokenize(sents[0])
print(words)

['What', 'are', 'you', 'doing', '?']


## Regular Expression

In [13]:
text="Email me all the 10 class learning assignments of the learn lecture L 1,2,3 at xsd@gmail.com"

In [14]:
sents=sent_tokenize(text)

In [15]:
from nltk.tokenize import RegexpTokenizer

In [16]:
reg_exp="[a-zA-Z@]+"

tokenizer=RegexpTokenizer(reg_exp)
text=tokenizer.tokenize(text)

In [17]:
from nltk.corpus import stopwords

In [18]:
stop=set(stopwords.words('english'))

In [19]:
print(stop)

{"mightn't", 't', 'that', "you've", 'other', 'who', 'shouldn', "should've", 'above', 'into', 'once', 'mustn', "hadn't", 'we', 'how', 'by', 'a', 'i', 'yourselves', 'does', 'about', 'here', 'this', 'now', 'own', 'yourself', "she's", 'himself', 'it', 'hasn', 'ours', 'such', 'doing', 'll', 'more', 's', 'don', 'o', 'them', "you're", 'had', 'over', 'or', "doesn't", 'yours', 'our', "wouldn't", 'its', 'then', 'those', 'aren', "didn't", 'their', 'her', 'couldn', 'not', 'will', 'off', 'through', 'too', 'which', "mustn't", "wasn't", 'from', 'm', 'against', 'be', 'been', 'what', 'is', 'did', 'to', 'ain', "you'd", "haven't", "aren't", "weren't", 'so', 'and', 'herself', 'theirs', 'has', 'nor', 'won', 'during', 'hadn', 'him', 'both', "shan't", 'weren', 'shan', 'under', 'doesn', 'have', "don't", 'any', 'wasn', 'just', 'having', 'same', 'there', 'ma', 'few', 'me', 'if', 'why', 'no', 'didn', 'were', 'itself', 'where', 'up', 'in', 'before', 'until', 'an', 'at', 'while', 'should', 'very', 'are', 'was', 'd

In [20]:
def remove_stopwords(sent,stopwords):
    useful_words=[w for w in sent if w not in stopwords]
    return useful_words

In [21]:
text=remove_stopwords(text,stop)
print(text)

['Email', 'class', 'learning', 'assignments', 'learn', 'lecture', 'L', 'xsd@gmail', 'com']


# Stemming

In [22]:
from nltk.stem.snowball import SnowballStemmer, PorterStemmer
from nltk.stem.lancaster import LancasterStemmer

In [23]:
ss=SnowballStemmer(language='english')

In [24]:
ls=LancasterStemmer()

In [25]:
ss.stem("jumping")

'jump'

In [26]:
ps=PorterStemmer()

In [27]:
ps.stem('learning')

'learn'

In [28]:
ps.stem('learn')

'learn'

In [29]:
ps.stem('running')

'run'

In [30]:
ps.stem("eat")

'eat'

In [31]:
ps.stem("mouse")

'mous'

In [32]:
ps.stem("teeth")

'teeth'

In [33]:
ps.stem("goose")

'goos'

In [34]:
ps.stem("gosling")

'gosl'

In [35]:
ps.stem("nokia")

'nokia'

In [36]:
ps.stem("abscess")

'abscess'

In [37]:
ps.stem("processing")

'process'

In [38]:
ps.stem("John")

'john'

In [39]:
ss.stem("general")

'general'

In [40]:
ls.stem("general")

'gen'

In [41]:
from nltk.stem import WordNetLemmatizer

In [42]:
wn=WordNetLemmatizer()

In [43]:
wn.lemmatize("resting")

'resting'

In [44]:
wn.lemmatize("morons")

'moron'

In [45]:
data=brown.sents(categories=['adventure'])[:4]

In [46]:
corpus=[' '.join(data[i]) for i in range(4)]
print(corpus)

['Dan Morgan told himself he would forget Ann Turner .', 'He was well rid of her .', "He certainly didn't want a wife who was fickle as Ann .", "If he had married her , he'd have been asking for trouble ."]


In [47]:
from sklearn.feature_extraction.text import CountVectorizer

In [48]:
cv=CountVectorizer()

In [49]:
vectorised_data=cv.fit_transform(corpus).toarray()
print (vectorised_data[0])

[1 0 0 0 0 1 0 0 0 1 0 0 1 0 1 0 0 1 0 0 1 0 1 0 0 0 0 0 1]


In [50]:
print ((cv.vocabulary_))


{'dan': 5, 'morgan': 17, 'told': 20, 'himself': 14, 'he': 12, 'would': 28, 'forget': 9, 'ann': 0, 'turner': 22, 'was': 24, 'well': 25, 'rid': 19, 'of': 18, 'her': 13, 'certainly': 4, 'didn': 6, 'want': 23, 'wife': 27, 'who': 26, 'fickle': 7, 'as': 1, 'if': 15, 'had': 10, 'married': 16, 'have': 11, 'been': 3, 'asking': 2, 'for': 8, 'trouble': 21}


In [51]:
cv.inverse_transform(vectorised_data[0])

[array(['ann', 'dan', 'forget', 'he', 'himself', 'morgan', 'told',
        'turner', 'would'], dtype='<U9')]

## Bag of Words

In [52]:
cv=CountVectorizer(tokenizer=tokenizer.tokenize)

In [53]:
cv.fit_transform(corpus).toarray()

array([[0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
        0, 1, 0, 1, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
        0, 0, 0, 0, 0, 1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 1, 1, 0, 1, 1, 0],
       [0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 2, 1, 0, 1, 1, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [54]:
cv.vocabulary_

{'dan': 7,
 'morgan': 19,
 'told': 23,
 'himself': 16,
 'he': 14,
 'would': 31,
 'forget': 11,
 'ann': 1,
 'turner': 25,
 'was': 27,
 'well': 28,
 'rid': 21,
 'of': 20,
 'her': 15,
 'certainly': 5,
 'didn': 8,
 't': 22,
 'want': 26,
 'a': 0,
 'wife': 30,
 'who': 29,
 'fickle': 9,
 'as': 2,
 'if': 17,
 'had': 12,
 'married': 18,
 'd': 6,
 'have': 13,
 'been': 4,
 'asking': 3,
 'for': 10,
 'trouble': 24}

# TF- IDF Normalization

In [55]:
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer

In [56]:
tf=TfidfVectorizer()
vd=tf.fit_transform(corpus).toarray()
print(vd)

[[0.28061238 0.         0.         0.         0.         0.35592122
  0.         0.         0.         0.35592122 0.         0.
  0.18573446 0.         0.35592122 0.         0.         0.35592122
  0.         0.         0.35592122 0.         0.35592122 0.
  0.         0.         0.         0.         0.35592122]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.24557576 0.37102215 0.         0.         0.         0.
  0.47059455 0.47059455 0.         0.         0.         0.
  0.37102215 0.47059455 0.         0.         0.        ]
 [0.27017662 0.34268479 0.         0.         0.34268479 0.
  0.34268479 0.34268479 0.         0.         0.         0.
  0.17882714 0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.34268479
  0.27017662 0.         0.34268479 0.34268479 0.        ]
 [0.         0.         0.32090095 0.32090095 0.         0.
  0.         0.       

In [57]:
print(vd[0])

[0.28061238 0.         0.         0.         0.         0.35592122
 0.         0.         0.         0.35592122 0.         0.
 0.18573446 0.         0.35592122 0.         0.         0.35592122
 0.         0.         0.35592122 0.         0.35592122 0.
 0.         0.         0.         0.         0.35592122]


In [58]:
tf.vocabulary_

{'dan': 5,
 'morgan': 17,
 'told': 20,
 'himself': 14,
 'he': 12,
 'would': 28,
 'forget': 9,
 'ann': 0,
 'turner': 22,
 'was': 24,
 'well': 25,
 'rid': 19,
 'of': 18,
 'her': 13,
 'certainly': 4,
 'didn': 6,
 'want': 23,
 'wife': 27,
 'who': 26,
 'fickle': 7,
 'as': 1,
 'if': 15,
 'had': 10,
 'married': 16,
 'have': 11,
 'been': 3,
 'asking': 2,
 'for': 8,
 'trouble': 21}

In [59]:
from sklearn.datasets import fetch_20newsgroups

In [60]:
newsgroups=fetch_20newsgroups()

In [61]:
Xa=newsgroups.data
Y=newsgroups.target_names

In [62]:
print(len(Xa))

11314


In [63]:
print(Xa[1])

From: guykuo@carson.u.washington.edu (Guy Kuo)
Subject: SI Clock Poll - Final Call
Summary: Final call for SI clock reports
Keywords: SI,acceleration,clock,upgrade
Article-I.D.: shelley.1qvfo9INNc3s
Organization: University of Washington
Lines: 11
NNTP-Posting-Host: carson.u.washington.edu

A fair number of brave souls who upgraded their SI clock oscillator have
shared their experiences for this poll. Please send a brief message detailing
your experiences with the procedure. Top speed attained, CPU rated speed,
add on cards and adapters, heat sinks, hour of usage per day, floppy disk
functionality with 800 and 1.4 m floppies are especially requested.

I will be summarizing in the next two days, so please add to the network
knowledge base if you have done the clock upgrade and haven't answered this
poll. Thanks.

Guy Kuo <guykuo@u.washington.edu>



In [64]:
Y

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [65]:
all_y=newsgroups.target

In [66]:
print(len(all_y))

11314


In [67]:
X=[Xa[i] for i in range(len(Xa)) if all_y[i]<=4]
print(len(X))

2823


In [82]:
tf=TfidfVectorizer()
t=tf.fit_transform(X).toarray()
print(t[8,9:-1])

MemoryError: 

In [83]:
X_train=t[:350]    
X_train=np.array(X_train)

In [80]:
X_test=np.array(t[350:])

MemoryError: 

In [81]:
print(X_test)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [71]:
Y_o=[Y[all_y[i]] for i in range(len(all_y)) if all_y[i]<=4]


In [72]:
Y_o=np.array(Y_o)
print(Y_o.shape)

(2823,)


In [73]:
Y_test=[Y[i] for i in all_y[650:] if i<=4]

In [74]:
def distance(p1,p2):
    return np.sum((p2 - p1)**2)**.5

In [75]:
def knn(X,Y,test,k=5):
    m = X.shape[0]
    
    d = []
    for i  in range(m):
        dist = distance(test,X[i])
        d.append((dist,Y[i]))
    
    d = np.array(sorted(d))[:,1]
    d = d[:k]
    t =  np.unique(d,return_counts=True)
    idx = np.argmax(t[1])
    pred = (t[0][idx])
    
    return pred
    

In [ ]:
print(Y_train[1])

In [ ]:
for i in range(X_test.shape[0]):
    print(knn(X_train,Y_train,X_test[i,:],8))

In [ ]:
tf=TfidfVectorizer()
=tf.fit_transform(X).toarray()
print(tf.vocabulary_)

In [ ]:
vd2=cv.fit_transform(X_train).toarray()